import Head from "next/head"
import BookHero from "../../Components/Book/BookHero/BookHero"
import Reviews from "../../Components/Book/Reviews/Reviews"
import Technology from "../../Components/Book/Technology/Technology"

function index() {
    return (
        <div>
            <Head>
                <title>NYD | Home</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <BookHero />
                <Technology />
                <Reviews />
            </main>
        </div>
    )
}

export default index