import Head from 'next/head'
import Carousel from '../Components/Home/Carousel/Carousel'
import Hero from '../Components/Home/Hero/Hero'
import Info1 from '../Components/Home/Info1/Info1'
import Info2 from '../Components/Home/Info2/Info2'
import Info3 from '../Components/Home/Info3/Info3'
import styles from '../Components/Home/Hero/Hero.module.css'
import Reviews from '../Components/Home/Reviews/Reviews'

export default function Home() {
  return (
    <div className={styles.App}>
      <Head>
        <title>NYD | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero />
        <Info1 />
        <Info2 />
        <Reviews />
        <Info3 />
      </main>

    </div >
  )
}
